name = "Hoyt"
license = "MIT"
licenselink = "https://github.com/musale/hoyt/blob/master/LICENSE"
description = "A simple theme for the people"
homepage = "https://musale.github.io/hoyt"
tags = ["syntax highlighting", "maxthjax", "rss", "gallery", "widgets", "google analytics"]
features = ["syntax highlighting", "maxthjax", "rss", "gallery", "widgets", "google analytics"]
min_version = "0.41"

[author]
  name = "Martin Musale"
  homepage = "https://musale.github.io"
